#!/usr/bin/env bash
SCRIPT_DIR=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
CONFIG_FILE=$SCRIPT_DIR/default_engine
ENGINE="$FLC_ENGINE"
if [ -z "$ENGINE" ] && [ -f "$CONFIG_FILE" ]
then
  ENGINE="$(cat "$CONFIG_FILE")"
fi
ENGINE="${ENGINE:-native}"
if [ "$ENGINE" = "native" ]
then
  exec "$SCRIPT_DIR/bin/linuxX64/flcReleaseExecutable/flc.kexe" "$@"
else
  echo "Unsupported engine: $ENGINE" 1>&2
  exit 1
fi
