on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Javaのセットアップ
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Gradleキャッシュの復元
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: gradle

      - name: リポジトリのチェックアウト（ビルド用）
        uses: actions/checkout@v4
        with:
          path: build-dir
          fetch-depth: 1

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
        with:
          path: build-dir

      - name: ビルド
        run: |
          cd build-dir
          bash gradlew build

      - name: リポジトリのチェックアウト（リリース用）
        uses: actions/checkout@v4
        with:
          path: release-dir
          ref: release
          fetch-depth: 1

      - name: ファイルの同期
        run: |
          mv release-dir/.git tmp92758927523654
          rsync -av --delete build-dir/release/ release-dir/
          rsync -av --delete build-dir/build/bin/ release-dir/bin/
          chmod a+x release-dir/*.sh
          mv tmp92758927523654 release-dir/.git

      - name: コミット準備
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "HASH=$(git -C build-dir rev-parse HEAD)" >> $GITHUB_ENV

      - name: コミット・リリース
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd release-dir
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit --allow-empty -m "v${{ env.VERSION }} - ${{ env.HASH }}"
          git push --force origin release
